server:
    port: 8888
spring:
    application:
        name: config-server
    cloud:
        config:
            server:
                native:
                    search-locations: classpath:/configurations
    profiles:
        active: native
logging:
    pattern:
        console: '%d{yyyy-MMM-dd HH:mm:s} %-5level - %msg%n'
