spring:
    application:
        name: product-service
    cloud:
        config:
            enabled: true
    config:
        import: optional:configserver:http://config-server:8888
info:
    app:
        name: "product-service"
        description: "product service for store-microservices (docker)"
        version: "1.0"