server:
    port: 8001
spring:
    application:
        name: product-service
    jpa:
        database: postgresql
        hibernate:
            ddl-auto: update
        show-sql: false
        properties:
            hibernate.format_sql: false
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/store
        username: username
        password: password
    config:
        import: optional:configserver:http://localhost:8888/
    servlet:
        multipart:
            enabled: true
            max-file-size: 2MB
            max-request-size: 5MB
eureka:
    instance:
        prefer-ip-address: true
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
management:
    endpoints:
        web:
            exposure:
                include: "*"
    info:
        env:
            enabled: true
    health:
        readiness-state:
            enabled: true
        liveness-state:
            enabled: true
    endpoint:
        health:
            probes:
                enabled: true
        shutdown:
            enabled: true
endpoints:
    shutdown:
        enabled: true
info:
    app:
        name: "product-service"
        description: "product service for store-microservices"
        version: "1.0"