server:
    port: 8000
spring:
    application:
        name: user-service
    jpa:
        database: postgresql
        hibernate:
            ddl-auto: update
        show-sql: false
        properties:
            hibernate.format_sql: false
    datasource:
        password: ${DATABASE_PASSWORD}
        driver-class-name: org.postgresql.Driver
        username: ${DATABASE_USERNAME}
        url: ${DATABASE_URL}/${DATABASE_NAME}
    config:
        import: optional:configserver:http://${CONFIG_SERVER_HOSTNAME}:${CONFIG_SERVER_PORT}/
password:
    encryption:
        key: ${PASSWORD_ENCRYPTION_KEY}
    decryption:
        key: ${PASSWORD_DECRYPTION_KEY}
eureka:
    instance:
        prefer-ip-address: true
    client:
        serviceUrl:
            defaultZone: http://${EUREKA_SERVER_HOSTNAME}:${EUREKA_SERVER_PORT}/eureka
management:
    endpoints:
        web:
            exposure:
                include: "*"
    info:
        env:
            enabled: true
    health:
        readiness-state:
            enabled: true
        liveness-state:
            enabled: true
    endpoint:
        health:
            probes:
                enabled: true
        shutdown:
            enabled: true
endpoints:
    shutdown:
        enabled: true
info:
    app:
        name: "userservice"
        description: "User Service for store-microservices"
        version: "1.0"