server:
    port: 8222
spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            default-filters:
                - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            globalcors:
                corsConfigurations:
                    '[/**]':
                        allowedOrigins: "*"
                        allowedMethods: "*"
                        allowedHeaders: "*"
            routes[2]:
                id: order-service
                uri: lb://ORDER-SERVICE
                predicates[0]: Path=/api/v1/orders/**, /api/v1/payments/**
            routes[1]:
                id: product-service
                uri: lb://PRODUCT-SERVICE
                predicates[0]: Path=/api/v1/products/**, /api/v1/categories/**
            routes[0]:
                id: user-service
                uri: lb://USER-SERVICE
                predicates[0]: Path=/api/v1/users/**, /api/v1/roles/**, /api/v1/addresses/**
eureka:
    client:
        serviceUrl:
            defaultZone: http://${EUREKA_SERVER_HOSTNAME}:${EUREKA_SERVER_PORT}/eureka
