spring:
    jpa:
        database: postgresql
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate.format_sql: true
    application:
        name: product-service
    datasource:
        password: password
        driver-class-name: org.postgresql.Driver
        username: username
        url: jdbc:postgresql://localhost:5432/store?currentSchema=products
logging:
    pattern:
        console: '%d{yyyy-MMM-dd HH:mm:s} %-5level - %msg%n'
server:
    port: '8001'
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
