server:
    port: 8001
spring:
    application:
        name: product-service
    jpa:
        database: postgresql
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate.format_sql: true
    datasource:
        password: ${DATABASE_PASSWORD}
        driver-class-name: org.postgresql.Driver
        username: ${DATABASE_USERNAME}
        url: ${DATABASE_URL}/${DATABASE_NAME}
eureka:
    client:
        serviceUrl:
            defaultZone: http://${EUREKA_SERVER_HOSTNAME}:${EUREKA_SERVER_PORT}/eureka
logging:
    pattern:
        console: '%d{yyyy-MMM-dd HH:mm:s} %-5level - %msg%n'