services:
    network-deploy-service:
        networks:
            - store-backend

    microservice-base-config:
        extends:
            service: network-deploy-service
        deploy:
            resources:
                limits:
                    memory: 700m

    eureka-config:
        extends:
            service: microservice-base-config
        environment:
            EUREKA_SERVER_HOSTNAME: eurekaserver
            EUREKA_SERVER_PORT: 8761

    gatewayservice-config:
        extends:
            service: eureka-config
        environment:
            CONFIG_SERVER_HOSTNAME: configserver
            CONFIG_SERVER_PORT: 8888