services:
    network-deploy-service:
        networks:
            - store-backend

    microservice-base-config:
        extends:
            service: network-deploy-service
        deploy:
            resources:
                limits:
                    memory: 700m

    eureka-server-config:
        extends:
            service: microservice-base-config
        environment:
            EUREKA_INSTANCE_HOSTNAME: eurekaserver
            EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka

    eureka-config-server-config:
        extends:
            service: eureka-server-config
        environment:
            SPRING_CONFIG_IMPORT: optional:configserver:http://configserver:8888/

    eureka-config-db-server-config:
        extends:
            service: eureka-config-server-config
        environment:
            SPRING_DATASOURCE_PASSWORD: password
            SPRING_DATASOURCE_USERNAME: username
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/store

    eureka-config-kafka-server-config:
        extends:
            service: eureka-config-server-config
        environment:
            SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:9092

    eureka-config-db-kafka-server-config:
        extends:
            service: eureka-config-db-server-config
        environment:
            SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:9092

    notification-service-config:
        extends:
            service: eureka-config-kafka-server-config
        environment:
            SPRING_MAIL_FROM: praveens-store@demomailtrap.com
            SPRING_MAIL_HOST: live.smtp.mailtrap.io
            SPRING_MAIL_PASSWORD: 4c6d189f9cb8c8072973cd447b21ebea
            SPRING_MAIL_USERNAME: api
            SPRING_MAIL_TO: praveenukkoji.dev@gmail.com

    payment-service-config:
        extends:
            service: eureka-config-db-kafka-server-config
        environment:
            FEIGN_CLIENT_CONFIG_ORDERSERVICE_URL: http://orderservice:8002/api/v1/orders

    order-service-config:
        extends:
            service: eureka-config-db-kafka-server-config
        environment:
            FEIGN_CLIENT_CONFIG_PRODUCTSERVICE_URL: http://productservice:8001/api/v1/products

    product-service-config:
        extends:
            service: eureka-config-db-server-config

    user-service-config:
        extends:
            service: eureka-config-db-server-config
        environment:
            PASSWORD_ENCRYPTION_KEY: 1234567890abcdef
            PASSWORD_DECRYPTION_KEY: 1234567890abcdef

    api-gateway-service-config:
        extends:
            service: eureka-config-server-config
        environment:
            SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: http://keycloak:8080/realms/master/protocol/openid-connect/certs