server:
    port: 8003
spring:
    application:
        name: payment-service
    cloud:
        config:
            enabled: false
        gateway:
            discovery:
                locator:
                    enabled: false
                    lowerCaseServiceId: true
    jpa:
        database: postgresql
        hibernate:
            ddl-auto: update
        show-sql: false
        properties:
            hibernate.format_sql: false
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/store
        username: username
        password: password
    kafka:
        bootstrap-servers: localhost:9092
        topic: paymentTopic
        producer:
            group-id: notification-service
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
feign:
    client:
        config:
            orderservice:
                url: http://localhost:8002/api/v1/orders
eureka:
    instance:
        prefer-ip-address: true
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
management:
    endpoints:
        web:
            exposure:
                include: "*"
    info:
        env:
            enabled: true
    health:
        readiness-state:
            enabled: true
        liveness-state:
            enabled: true
    endpoint:
        health:
            probes:
                enabled: true
        shutdown:
            enabled: true
endpoints:
    shutdown:
        enabled: true
info:
    app:
        name: "payment-service"
        description: "payment service for store-microservices"
        version: "1.0"