spring:
    application:
        name: payment-service
    cloud:
        config:
            enabled: true
    config:
        import: optional:configserver:http://config-server:8888
info:
    app:
        name: "payment-service"
        description: "payment service for store-microservices (docker)"
        version: "1.0"