spring:
    application:
        name: user-service
    cloud:
        config:
            enabled: true
    config:
        import: optional:configserver:http://config-server:8888
info:
    app:
        name: "user-service"
        description: "user service for store-microservices (docker)"
        version: "1.0"