server:
    port: 8003
spring:
    application:
        name: notification-service
    kafka:
        bootstrap-servers: ${KAFKA_SERVER_HOSTNAME}:${KAFKA_SERVER_PORT}
        template:
            default-topic: orderTopic
        consumer:
            group-id: orderEventId
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            properties:
                spring:
                    json:
                        type:
                            mapping: event:com.praveenukkoji.notificationservice.event.OrderEvent
    config:
        import: optional:configserver:http://${CONFIG_SERVER_HOSTNAME}:${CONFIG_SERVER_PORT}/
eureka:
    instance:
        prefer-ip-address: true
    client:
        serviceUrl:
            defaultZone: http://${EUREKA_SERVER_HOSTNAME}:${EUREKA_SERVER_PORT}/eureka
management:
    endpoints:
        web:
            exposure:
                include: "*"
    info:
        env:
            enabled: true
    health:
        readiness-state:
            enabled: true
        liveness-state:
            enabled: true
    endpoint:
        health:
            probes:
                enabled: true
        shutdown:
            enabled: true
endpoints:
    shutdown:
        enabled: true
info:
    app:
        name: "notificationservice"
        description: "Notification Service for store-microservices"
        version: "1.0"