server:
    port: 8003
spring:
    application:
        name: notification-service
    kafka:
        bootstrap-servers: localhost:9092
        template:
            default-topic: orderTopic
        consumer:
            group-id: orderEventId
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            properties:
                spring:
                    json:
                        type:
                            mapping: event:com.praveenukkoji.notificationservice.event.OrderEvent
    config:
        import: optional:configserver:http://localhost:8888/
    mail:
        host: ${MAILTRAP_HOST}
        port: 587
        username: ${MAILTRAP_USERNAME}
        password: ${MAILTRAP_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: false
                    starttls:
                        enable: true
        to: ${TO}
        from: ${FROM}
eureka:
    instance:
        prefer-ip-address: true
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
management:
    endpoints:
        web:
            exposure:
                include: "*"
    info:
        env:
            enabled: true
    health:
        readiness-state:
            enabled: true
        liveness-state:
            enabled: true
    endpoint:
        health:
            probes:
                enabled: true
        shutdown:
            enabled: true
endpoints:
    shutdown:
        enabled: true
info:
    app:
        name: "notificationservice"
        description: "Notification Service for store-microservices"
        version: "1.0"