spring:
    application:
        name: notification-service
    cloud:
        config:
            enabled: true
    config:
        import: optional:configserver:http://config-server:8888
info:
    app:
        name: "notificationservice"
        description: "notification service for store-microservices (docker)"
        version: "1.0"