version: '3.8'

services:
    postgres:
        container_name: db
        image: postgres
        environment:
            POSTGRES_USER: username
            POSTGRES_PASSWORD: password
            PGDATA: /var/lib/postgresql/data
            POSTGRES_DB: store
        volumes:
            - postgres:/data/postgres
        ports:
            - "5432:5432"
        networks:
            - store-backend
        restart: unless-stopped

networks:
    store-backend:
        driver: bridge

volumes:
    postgres:
        driver: local
