server:
    port: 8002
spring:
    application:
        name: order-service
    jpa:
        database: postgresql
        hibernate:
            ddl-auto: update
        show-sql: false
        properties:
            hibernate.format_sql: false
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/store
        username: username
        password: password
    kafka:
        bootstrap-servers: localhost:9092
        template:
            default-topic: orderTopic
        producer:
            group-id: orderEventId
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
            properties:
                spring:
                    json:
                        type:
                            mapping: event:com.praveenukkoji.orderservice.kafka.event.OrderEvent
    config:
        import: optional:configserver:http://localhost:8888/
feign:
    client:
        config:
            productservice:
                url: http://localhost:8001/api/v1/products
eureka:
    instance:
        prefer-ip-address: true
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
management:
    endpoints:
        web:
            exposure:
                include: "*"
    info:
        env:
            enabled: true
    health:
        readiness-state:
            enabled: true
        liveness-state:
            enabled: true
    endpoint:
        health:
            probes:
                enabled: true
        shutdown:
            enabled: true
endpoints:
    shutdown:
        enabled: true
info:
    app:
        name: "order-service"
        description: "order service for store-microservices"
        version: "1.0"