server:
    port: 7002
spring:
    application:
        name: order-service
    datasource:
        url: jdbc:postgresql://postgres:5432/store
        username: username
        password: password
    kafka:
        bootstrap-servers: kafka:9092
feign:
    client:
        config:
            productservice:
                url: http://productservice:7001/api/v1/products
eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka-server:8761/eureka