management:
    endpoints:
        web:
            exposure:
                include: '*'
    endpoint:
        health:
            show-details: always
spring:
    boot:
        admin:
            client:
                instance:
                    service-base-url: http://localhost:8002
                    name: order-service
                url: http://localhost:9090/
    jpa:
        database: postgresql
        hibernate:
            ddl-auto: update
        show-sql: 'true'
        format-sql: 'true'
    application:
        name: order-service
    datasource:
        password: ${db_password}
        driver-class-name: org.postgresql.Driver
        username: ${db_username}
        url: jdbc:postgresql://localhost:5432/${db_name}
logging:
    pattern:
        console: '%d{yyyy-MMM-dd HH:mm:s} %-5level - %msg%n'
server:
    port: '8002'
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
