server:
    port: 7003
spring:
    application:
        name: payment-service
    datasource:
        url: jdbc:postgresql://postgres:5432/store
        username: username
        password: password
    kafka:
        bootstrap-servers: kafka:9092
feign:
    client:
        config:
            orderservice:
                url: http://orderservice:7002/api/v1/orders
eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka-server:8761/eureka