server:
    port: 8222
spring:
    application:
        name: api-gateway
    config:
        import: optional:configserver:http://${CONFIG_SERVER_HOSTNAME}:${CONFIG_SERVER_PORT}/
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: false
                    lowerCaseServiceId: true
    security:
        oauth2:
            resourceserver:
                jwt:
                    jwk-set-uri: "http://localhost:8080/realms/master/protocol/openid-connect/certs"
eureka:
    instance:
        prefer-ip-address: true
    client:
        serviceUrl:
            defaultZone: http://${EUREKA_SERVER_HOSTNAME}:${EUREKA_SERVER_PORT}/eureka
management:
    endpoints:
        web:
            exposure:
                include: "*"
    info:
        env:
            enabled: true
    health:
        readiness-state:
            enabled: true
        liveness-state:
            enabled: true
    endpoint:
        gateway:
            enabled: true
        health:
            probes:
                enabled: true
        shutdown:
            enabled: true
endpoints:
    shutdown:
        enabled: true
info:
    app:
        name: "api-gateway"
        description: "API Gateway for store-microservices"
        version: "1.0"